### ISSUE TITLE
fanc compare error

### ISSUE THREAD

**Issue by xinyangbing** [vaquerizaslab/fanc#29]
Hi,

I seem to be running into a couple of different types of errors when executing fanc compare on separate datasets (the command also takes many days to run its course and ends up generating the file, but it seems incomplete):

PATH=$PATH:/Genomics/grid/users/xbing/miniconda3/bin
source activate snakes
module load hdf5/1.8.8
fanc compare M_23del.cool M_WT.cool 23del_WT
2020-10-19 13:22:32,009 INFO FAN-C version: 0.9.4
2020-10-19 18:54:53,547 INFO Calculating scaling factor...
Traceback (most recent call last):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/bin/fanc", line 127, in <module>
    Fanc()
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 
3358, in compare
    oe=oe, norm=norm, log=log_matrix)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/architecture/comparisons.py", lin
e 287, in from_matrices
    for edge in matrix1.edges((chromosome1, chromosome2), **kwargs):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/matrix.py", line 755, in __call__
    *args, **kwargs):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 42
6, in _edges_subset
    yield self._series_to_edge(row, lazy_edge=lazy_edge, *args, **kwargs)
TypeError: _series_to_edge() got an unexpected keyword argument 'mode'
Closing remaining open files:23del_WT...done

And the other one:
fanc compare M_TADdel.cool M_WT.cool TADdel_WT
2020-10-22 10:02:53,594 INFO FAN-C version: 0.9.4
2020-10-22 14:57:29,657 INFO Calculating scaling factor...
Traceback (most recent call last):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/bin/fanc", line 127, in <module>
    Fanc()
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 
3358, in compare
    oe=oe, norm=norm, log=log_matrix)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/architecture/comparisons.py", lin
e 274, in from_matrices
    sf = matrix2.scaling_factor(matrix1)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/matrix.py", line 1312, in scaling
_factor
    for v2 in matrix.edge_data(weight_column, lazy=True):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/matrix.py", line 848, in edge_dat
a
    for edge in self.edges(*args, **kwargs):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/matrix.py", line 696, in __call__
    bias = self._regions_pairs.bias_vector()
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 45
6, in bias_vector
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 45
6, in <listcomp>
    return np.array([r.bias for r in self.regions(lazy=True)])
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 22
1, in __getattr__
    return getattr(self._series, item)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/pandas/core/generic.py", line 5139, in
 __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'bias'
Closing remaining open files:TADdel_WT...done

Please help! Thank you!

**Comment by liz-is** [comment]
Hi David!

Kai will know better than I do, but I have a couple of suggestions in the mean time. 

First of all I'd suggest updating to the most recent version (0.9.7) - I can see a couple of changes that have been made since 0.9.4 that are related to handling of cooler files, so this might be a known bug that's already fixed. You can try comparing at low resolution to see if this fixes the issue, hopefully without it taking too long.

Second, I wouldn't expect `fanc compare` to take days to run... it may well be faster to convert from .cool to FAN-C .hic format first, and compare those files. Cooler format doesn't store the expected values, so having to (re)compute these can slow things down. 

If updating to the most recent version of FAN-C doesn't solve the issue, it might also be helpful to know the cooler version that was used to create these files, in case it's related to changes in cooler.

**Comment by kaukrise** [comment]
Hi David,

the first error is definitely a FAN-C issue, which I need to fix. I already know where the problem lies, and I'll get to it asap.

The second error can most likely be fixed by upgrading, as @liz-is already mentioned, but you can wait until I fixed and tested the other issue.

Regarding the runtime: Can you let me know what resolution the files are that you are comparing? If these are extremely high resolution (like <5kb) comparisons can take really long, especially for Cooler files. Converting to FAN-C will help a bit with the runtime, but if you have specific regions in mind, you may want to subset the matrix first and then run `compare` on those instead.

I'll keep you updated on the other issue.

**Comment by kaukrise** [comment]
Here is a version with a potential fix - would you kindly test it out on your data?

[fanc-0.9.8.tar.gz](https://github.com/vaquerizaslab/fanc/files/5519485/fanc-0.9.8.tar.gz)

You can instal it on your machine after downloading with

```
pip install fanc-0.9.8.tar.gz
```

Then check that you are indeed running the latest version with

```
fanc -V
```

Another option to speed the comparison up is to skip the calculation of the scaling factor. I don't know how your cooler files were normalised, so I don't recomment that as an option for those, but if you end up converting to FAN-C, and then re-normalise with

```
fanc hic -n <FAN-C Hi-C file>
```

all entires are interpretable as contact probabilities, and thus directly comparable between matrices. Then you can enable the `-S` option in `fanc compare` to skip the scaling factor calculation, which takes very long.

Cheers,

Kai

**Comment by xinyangbing** [comment]
Hi Kai,

Thank you for the suggestions. I was able to convert a few cool files to hic format using FANC. But one of the cool files led to this error message (I tried remapping the file from fastq, but am still getting the same error):
fanc from-cooler M_TADdelall.cool M_TADdel.hic:
2020-11-27 12:28:34,878 INFO FAN-C version: 0.9.8
Traceback (most recent call last):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/bin/fanc", line 127, in <module>
    Fanc()
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/bin/fanc", line 93, in __init__
    command([sys.argv[0]] + sys.argv[option_ix:], log_level=log_level, verbosity=verbosity)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/commands/fanc_commands.py", line 1850, in
 from_cooler
    cool.deepcopy(fanc.Hic, file_name=output_file, mode='w')
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/matrix.py", line 1324, in deepcopy
    copy.add_regions(self.regions(lazy=True))
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/regions.py", line 664, in add_regions
    self.add_region(region, *args, **kwargs)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/genomic_regions/regions.py", line 1199, in add
_region
    return self._add_region(region.copy(), *args, **kwargs)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/genomic_regions/regions.py", line 505, in copy
    d = {attribute: getattr(self, attribute) for attribute in self.attributes}
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/genomic_regions/regions.py", line 505, in <dic
tcomp>
    d = {attribute: getattr(self, attribute) for attribute in self.attributes}
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/fanc/compatibility/cooler.py", line 221, in __
getattr__
    return getattr(self._series, item)
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/pandas/core/generic.py", line 5139, in __getat
tr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'weight'
Closing remaining open files:M_TADdel.hic...done
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/tables/node.py", line 319, in __del__
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/tables/table.py", line 2961, in _f_close
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/tables/table.py", line 2896, in flush
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/tables/table.py", line 626, in autoindex
  File "/Genomics/grid/users/xbing/miniconda3/envs/snakes/lib/python3.6/site-packages/tables/file.py", line 1590, in _get_node
AttributeError: 'File' object has no attribute '_node_manager'

Also, I tried plotting an O/E matrix from one of the converted hic files, and cannot seem to get any blue, and the plot is really sparse. 
![Kni_knrl_OEtest](https://user-images.githubusercontent.com/55600546/100485460-21005c00-30ce-11eb-9a9f-6687b453c179.png)
I then realized that this must be because I did not normalise the new hic data, but when I tried to normalize the data using the command you wrote, I get this message:
fancplot chr3L:20590000-20710000 -p square -e -vmin 0.01 -vmax 0.01 M_WT.hic
2020-11-27 16:26:31,777 INFO Found 1 regions
Closing remaining open files:M_WT.hic...done

Please help, thank you! Sorry for the multi-part question...
David

**Comment by kaukrise** [comment]
Hey,

I have uploaded a new version of FAN-C to PyPi (`0.9.9`) that should fix both of the issues you are seeing. If you're interested in the details: 

1. The recent change in FAN-C to speed up Cooler file handling broke the Cooler region attribute list, which is only used for region copying and thus went unnoticed
2. The bias vector returned by Cooler can return NaNs for unmappable regions, which broke the expected value calculation. I am now ensuring that each bias vector entry is finite for FAN-C compatibility

One note: If you use `--deepcopy`, FAN-C will attempt to use the existing bias vector from the Cooler file, so there is no explicit need for re-normalisation. I only recommended it above to ensure matrices are directly comparable, which allows you to use the `-S` option in `fanc compare` to speed up the comparison.

You will need to re-run the Cooler to FAN-C conversion and the should be able to see the proper O/E matrix! Let me know if you run into further issue.

**Comment by xinyangbing** [comment]
Hi Kai,
I am trying --deepcopy, but also I re-tried the normalization procedure you suggested before to check, and that is now leading to slurm killing the job because of memory limitations:
2021-01-08 20:04:20,314 INFO FAN-C version: 0.9.9
2021-01-08 20:04:20,723 INFO Normalising binned Hic file
/var/spool/slurmd/job37413947/slurm_script: line 12: 26039 Killed                  fanc hic -n M_WT_noloopsattbs
.hic
2021-01-08 20:23:32,555 INFO FAN-C version: 0.9.9
2021-01-08 20:23:32,917 INFO Normalising binned Hic file
slurmstepd: error: *** JOB 37413947 ON cetus-c1-15 CANCELLED AT 2021-01-08T20:24:56 ***
slurmstepd: error: Detected 1 oom-kill event(s) in step 37413947.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.

Just wanted to give you a heads up on this. Also, I was trying to plot a virtual4Cplot that Liz was using, but could not find any listing for it in the Python API. I could only find HiCsliceplot. Also, I was wondering if there is a way I could output the data generated from virtual4Cplot into a text file so I could plot it myself and avoid plotting in API with unfamiliar python language. 

Thank you for the help!

**Comment by xinyangbing** [comment]
Hi Kai,
Quick question about scaling during compare function. I subset my cooler converted hic files, and then did compare on the subset data to save time. But I realized when I plotted different comparisons that the O/E plots look slightly different depending on sequencing depth of the libraries. Does the scaling calculation depend on the entire dataset to properly scale? I guess all of this could be avoided if I just used the "deepcopy" function during conversion? Please let me know, thank you!

**Comment by kaukrise** [comment]
Hi, thanks for the feedback.

For your memory issue, you can use ICE norm, which is much more memory efficient, with little difference in end result (`--norm-method ICE`).

@liz-is already made me aware of the partially redundant Virtual4CPlot and HicSlicePlot, I'll see if I can improve the docs about that at some point. There is no straightforward way of exporting the values from a plot to txt file, as we only provide plotting capability within Python. But you might be a able to modify this code to generate and export the values from the V4C plot (I haven't tested it, though):

```python
import fanc
import numpy as np
import pandas as pd

hic = fanc.load("/path/to/file.hic")
viewpoint = 'chr3:5mb-5.25mb'
region = 'chr3:7mb-8mb'

# get y values
submatrix = hic.matrix((viewpoint, region), norm=True, oe=False)
v4c_signal = np.nanmean(submatrix, axis=0)

# get x values
x = []
for r in hic.regions(region):
    x.append(r.center)

# export to CSV
df = pd.DataFrame({'x': x, 'y': v4c_signal})
df.to_csv('/path/to/file.csv')

```

Regarding your question about scaling: yes, the comparison function computes the scaling factor on all pixels available in the dataset. Ideally you provide per-chromosome normalised files, where pixels can be interpreted as contact probabilities. This is what `fanc hic -n` does (either using the default or `--norm-method ICE`). Then you can disable scaling with the `-S` option.

**Comment by xinyangbing** [comment]
Hey Kai,
So I tried the ICR normalization method that you suggested. While the memory usage was manageable, the end result hic files generated plots that looked quite weird:
![WT_ICE](https://user-images.githubusercontent.com/55600546/105275009-612f0880-5b6c-11eb-9ba5-b92348de2b70.png)
This almost reminds me of when I used to normalize after I bin the data using cooler, the data looks very strippy. I did not get this when I was not normalizing the data, and just using the hic files directly converted from un-normalized cool files. Do you know if this is normal? 

Also, I tried the code you wrote. It works beautifully. Weirdly, when I tried doing the same thing with the hic files that were ICE normalized, it's giving me values that are orders of magnitude larger than originally with the unnormalized hic files from the same cool file. For example, previously I was getting like 0.2 and now I'm getting 20. And the weird stripy matrix generated from fancplot with the normalized data gives me pause. Could you explain why the values are shifting decimals? I thought that the normalized data was supposed to be contact probability? 

Thank you for the help!

**Comment by xinyangbing** [comment]
![WTnoloops_400_Norm](https://user-images.githubusercontent.com/55600546/105275621-c5060100-5b6d-11eb-8fbd-5496bed4ceb5.png)
Sorry, I was mistaken. This was the fancplot from the same region when I normalized with the standard method (KR). For some reason KR was working here, but for larger datasets it is taking too much memory and getting killed?

**Comment by kaukrise** [comment]
Hi, thanks for reporting back.

I'm sorry, but I am not sure which of the issues you mention still persists.

- ICE norm
  - Does the ICE norm give you normalised values larger than 1? If that is the case, can you please post the log of the FAN-C command where you did the normalisation?
  - Did you use the full matrix for normalisation or did you subset?
  - Can you please post images of the matrices before and after ICE normalisation, preferably in the same region you posted above?
- Stripes
  - Can you please list once again under what circumstances you are getting these stripes, with all intermediate commands?  (Converted from Cooler, ICE norm, comparison?)
- Memory during KR norm
  - The KR norm code used full chromosome matrices - if these don't fit in memory, the normalisation command is going to crash. This is likely why it worked for the subset matrices. ICE norm just iterates over all matrix pixels, and it much more memory friendly, hence my suggestion to use that instead. I would recommend to always check the logs of your FAN-C commands for any errors.

Thanks!

**Comment by xinyangbing** [comment]
Hi Kai,

I am terribly sorry for the inconvenience, but all of this arose because when I wrote the new pipeline based on ICE normalization, I accidentally put the normalization step in front of the binning, and this of course led to the stripy pattern I saw, and the weird normalized numbers. 

Thank you for clarifying the ICE vs KR normalization. I notice subtle differences between ICE normalized and KR normalized matrices, with some loops seemingly stronger. Is there a field standard as to which one is better or is it simply better to pick one and stay consistent? It seems that 4DN uses ICE, so I assume that cooler balancing uses that? I cannot seem to find it in their github writeup...

While we are at it, I was wondering if you could look over the pipeline I'm running quickly to see if it's all kosher:
fanc from-cooler WT1.cool WT1.hic
fanc hic -b 400 WT1.hic ./binned_output/WT1_400.hic
fanc hic -n --norm-method ICE WT1_400.hic
After this I use your script to generate virtual4C plotting data. 

Thank you so much for your help, and terribly sorry again for wasting your time! 
David

**Comment by kaukrise** [comment]
Hi David,

don't worry, this is no problem at all. I'm just glad this is resolved!

I don't think there is a consensus in the field which normalisation to prefer, and I am also not an expert on the mathematical side of things. As far as I know, KR was applied to Hi-C first [here](https://www.cell.com/fulltext/S0092-8674(14)01497-4), where they remark in the Supplement "Recently, Knight and Ruiz introduced a new matrix balancing algorithm whose convergence properties closely resemble those of the Sinkhorn-Knopp algorithm [ICE], but which converges much faster (Knight and Ruiz, 2012)". So if I understand correctly, the two should be largely equivalent (given infinite iterations of ICE?), but KR ist faster and "numerically stable". Cooler also uses ICE balancing internally, as far as I know. I think choosing one and sticking with it is a good choice.

Your pipeline looks good, though I do have a questions and a comment, mostly out of curiosity:

- I gather from your commands that your Cooler file is single resolution (not `.mcool`). May I ask what resolution that is? Or is this a fragment-level Hi-C file?
- If you want, you can combine the second and third commands into `fanc hic -n --norm-method ICE -b 400 WT1.hic ./binned_output/WT1_400.hic`. The normalisation will then always be after binning!

**Comment by xinyangbing** [comment]
Hi Kai,
My cooler file was generated at 100bp resolution from Micro-C, when I use cooler to make the mcool file it makes the other bins for me. 
I actually think I found a weird behavior in ICE, but unfortunately I cannot provide the log file because when I ran it I checked the log, everything looked normal, and I deleted it (sorry). Here's the problem:
![WT2_ICE](https://user-images.githubusercontent.com/55600546/105873680-bbdfbe80-5fc9-11eb-959c-6ef60c8fdb3d.png)
![WT2_KR](https://user-images.githubusercontent.com/55600546/105873682-bc785500-5fc9-11eb-9e98-9a42a71c722b.png)
These are two fancplots from the same dataset. One was normalized with KR (the default) and one from ICE. As you can see in the ICE image, there is one bin with less interactions than expected, but only in ICE. I have noticed this happening spontaneously in various loci, at different locations, in different samples. I ran the command I showed you before, 
fanc from-cooler WT2.cool WT2.hic
fanc hic -b 400 WT1.hic ./binned_output/WT2_400.hic
fanc hic -n --norm-method ICE WT2_400.hic

David

**Comment by xinyangbing** [comment]
Here's the log:
2021-01-22 05:48:25,268 INFO FAN-C version: 0.9.9
2021-01-22 05:48:25,736 INFO Normalising binned Hic file
2021-01-22 05:48:25,736 INFO Starting ICE matrix balancing
2021-01-22 11:55:07,286 INFO Done.
2021-01-22 11:55:07,286 INFO Adding bias vector...
2021-01-22 11:55:07,286 INFO Done.
Expected N/A% (0 of 81492023) |          | Elapsed Time: 0:00:00 ETA:  --:--:--
Expected   0% (1 of 81492023) |          | Elapsed Time: 0:00:00 ETA:  00:00:00
Expected   1% (814921 of 81492023) |     | Elapsed Time: 0:00:05 ETA:   0:08:25
Expected   2% (1629841 of 81492023) |    | Elapsed Time: 0:00:10 ETA:   0:08:41
Expected   3% (2444761 of 81492023) |    | Elapsed Time: 0:00:15 ETA:   0:08:37
Expected   4% (3259681 of 81492023) |    | Elapsed Time: 0:00:21 ETA:   0:08:28
Expected   5% (4074602 of 81492023) |    | Elapsed Time: 0:00:26 ETA:   0:08:17
Expected   6% (4889522 of 81492023) |    | Elapsed Time: 0:00:31 ETA:   0:08:05
Expected   7% (5704442 of 81492023) |    | Elapsed Time: 0:00:36 ETA:   0:08:05
Expected   8% (6519362 of 81492023) |    | Elapsed Time: 0:00:41 ETA:   0:07:58
Expected   9% (7334283 of 81492023) |    | Elapsed Time: 0:00:47 ETA:   0:07:57
Expected  10% (8149203 of 81492023) |    | Elapsed Time: 0:00:52 ETA:   0:07:43
Expected  11% (8964123 of 81492023) |    | Elapsed Time: 0:00:57 ETA:   0:07:43
Expected  12% (9779043 of 81492023) |    | Elapsed Time: 0:01:02 ETA:   0:07:34
Expected  13% (10593963 of 81492023) |   | Elapsed Time: 0:01:07 ETA:   0:07:27
Expected  14% (11408884 of 81492023) |   | Elapsed Time: 0:01:13 ETA:   0:08:05
Expected  15% (12223804 of 81492023) |   | Elapsed Time: 0:01:19 ETA:   0:08:11
Expected  16% (13038724 of 81492023) |   | Elapsed Time: 0:01:25 ETA:   0:08:20
Expected  17% (13853644 of 81492023) |   | Elapsed Time: 0:01:31 ETA:   0:08:22
Expected  18% (14668565 of 81492023) |   | Elapsed Time: 0:01:37 ETA:   0:09:08
Expected  19% (15483485 of 81492023) |   | Elapsed Time: 0:01:44 ETA:   0:08:40
Expected  20% (16298405 of 81492023) |   | Elapsed Time: 0:01:51 ETA:   0:08:55
Expected  21% (17113325 of 81492023) |   | Elapsed Time: 0:01:57 ETA:   0:08:19
Expected  22% (17928246 of 81492023) |   | Elapsed Time: 0:02:03 ETA:   0:08:27
Expected  23% (18743166 of 81492023) |   | Elapsed Time: 0:02:11 ETA:   0:09:30
Expected  24% (19558086 of 81492023) |   | Elapsed Time: 0:02:18 ETA:   0:09:37
Expected  25% (20373006 of 81492023) |   | Elapsed Time: 0:02:25 ETA:   0:08:16
Expected  26% (21187926 of 81492023) |   | Elapsed Time: 0:02:30 ETA:   0:06:42
Expected  27% (22002847 of 81492023) |   | Elapsed Time: 0:02:36 ETA:   0:06:23
Expected  28% (22817767 of 81492023) |   | Elapsed Time: 0:02:41 ETA:   0:06:14
Expected  29% (23632687 of 81492023) |   | Elapsed Time: 0:02:46 ETA:   0:06:10
Expected  30% (24447607 of 81492023) |   | Elapsed Time: 0:02:51 ETA:   0:06:04
Expected  31% (25262528 of 81492023) |   | Elapsed Time: 0:02:57 ETA:   0:06:06
Expected  32% (26077448 of 81492023) |   | Elapsed Time: 0:03:02 ETA:   0:05:52
Expected  33% (26892368 of 81492023) |   | Elapsed Time: 0:03:07 ETA:   0:05:45
Expected  34% (27707288 of 81492023) |#  | Elapsed Time: 0:03:12 ETA:   0:05:39
Expected  35% (28522209 of 81492023) |#  | Elapsed Time: 0:03:17 ETA:   0:05:35
Expected  36% (29337129 of 81492023) |#  | Elapsed Time: 0:03:22 ETA:   0:05:30
Expected  37% (30152049 of 81492023) |#  | Elapsed Time: 0:03:28 ETA:   0:05:22
Expected  38% (30966969 of 81492023) |#  | Elapsed Time: 0:03:34 ETA:   0:07:02
Expected  39% (31781889 of 81492023) |#  | Elapsed Time: 0:03:41 ETA:   0:06:26
Expected  40% (32596810 of 81492023) |#  | Elapsed Time: 0:03:49 ETA:   0:08:00
Expected  41% (33411730 of 81492023) |#  | Elapsed Time: 0:03:56 ETA:   0:06:40
Expected  42% (34226650 of 81492023) |#  | Elapsed Time: 0:04:02 ETA:   0:06:23
Expected  43% (35041570 of 81492023) |#  | Elapsed Time: 0:04:10 ETA:   0:07:20
Expected  44% (35856491 of 81492023) |#  | Elapsed Time: 0:04:17 ETA:   0:06:17
Expected  45% (36671411 of 81492023) |#  | Elapsed Time: 0:04:24 ETA:   0:06:58
Expected  46% (37486331 of 81492023) |#  | Elapsed Time: 0:04:30 ETA:   0:04:59
Expected  47% (38301251 of 81492023) |#  | Elapsed Time: 0:04:35 ETA:   0:04:41
Expected  48% (39116172 of 81492023) |#  | Elapsed Time: 0:04:40 ETA:   0:04:32
Expected  49% (39931092 of 81492023) |#  | Elapsed Time: 0:04:46 ETA:   0:04:36
Expected  50% (40746012 of 81492023) |#  | Elapsed Time: 0:04:51 ETA:   0:04:26
Expected  51% (41560932 of 81492023) |#  | Elapsed Time: 0:04:56 ETA:   0:04:24
Expected  52% (42375852 of 81492023) |#  | Elapsed Time: 0:05:02 ETA:   0:04:12
Expected  53% (43190773 of 81492023) |#  | Elapsed Time: 0:05:07 ETA:   0:04:05
Expected  54% (44005693 of 81492023) |#  | Elapsed Time: 0:05:12 ETA:   0:04:02
Expected  55% (44820613 of 81492023) |#  | Elapsed Time: 0:05:18 ETA:   0:04:00
Expected  56% (45635533 of 81492023) |#  | Elapsed Time: 0:05:23 ETA:   0:03:48
Expected  57% (46450454 of 81492023) |#  | Elapsed Time: 0:05:28 ETA:   0:03:44
Expected  58% (47265374 of 81492023) |#  | Elapsed Time: 0:05:33 ETA:   0:03:45
Expected  59% (48080294 of 81492023) |#  | Elapsed Time: 0:05:38 ETA:   0:03:32
Expected  60% (48895214 of 81492023) |#  | Elapsed Time: 0:05:44 ETA:   0:03:58
Expected  61% (49710135 of 81492023) |#  | Elapsed Time: 0:05:50 ETA:   0:03:51
Expected  62% (50525055 of 81492023) |#  | Elapsed Time: 0:05:56 ETA:   0:03:45
Expected  63% (51339975 of 81492023) |#  | Elapsed Time: 0:06:02 ETA:   0:03:41
Expected  64% (52154895 of 81492023) |#  | Elapsed Time: 0:06:08 ETA:   0:03:38
Expected  65% (52969815 of 81492023) |#  | Elapsed Time: 0:06:16 ETA:   0:04:23
Expected  66% (53784736 of 81492023) |#  | Elapsed Time: 0:06:23 ETA:   0:03:46
Expected  67% (54599656 of 81492023) |## | Elapsed Time: 0:06:31 ETA:   0:04:42
Expected  68% (55414576 of 81492023) |## | Elapsed Time: 0:06:38 ETA:   0:03:46
Expected  69% (56229496 of 81492023) |## | Elapsed Time: 0:06:44 ETA:   0:02:44
Expected  70% (57044417 of 81492023) |## | Elapsed Time: 0:06:57 ETA:   0:06:33
Expected  71% (57859337 of 81492023) |## | Elapsed Time: 0:07:09 ETA:   0:06:01
Expected  72% (58674257 of 81492023) |## | Elapsed Time: 0:07:18 ETA:   0:04:06
Expected  73% (59489177 of 81492023) |## | Elapsed Time: 0:07:36 ETA:   0:08:04
Expected  74% (60304098 of 81492023) |## | Elapsed Time: 0:07:44 ETA:   0:03:27
Expected  75% (61119018 of 81492023) |## | Elapsed Time: 0:07:49 ETA:   0:02:10
Expected  76% (61933938 of 81492023) |## | Elapsed Time: 0:07:54 ETA:   0:02:05
Expected  77% (62748858 of 81492023) |## | Elapsed Time: 0:08:00 ETA:   0:02:00
Expected  78% (63563778 of 81492023) |## | Elapsed Time: 0:08:05 ETA:   0:01:52
Expected  79% (64378699 of 81492023) |## | Elapsed Time: 0:08:10 ETA:   0:01:48
Expected  80% (65193619 of 81492023) |## | Elapsed Time: 0:08:15 ETA:   0:01:45
Expected  81% (66008539 of 81492023) |## | Elapsed Time: 0:08:20 ETA:   0:01:38
Expected  82% (66823459 of 81492023) |## | Elapsed Time: 0:08:25 ETA:   0:01:33
Expected  83% (67638380 of 81492023) |## | Elapsed Time: 0:08:31 ETA:   0:01:27
Expected  84% (68453300 of 81492023) |## | Elapsed Time: 0:08:36 ETA:   0:01:23
Expected  85% (69268220 of 81492023) |## | Elapsed Time: 0:08:41 ETA:   0:01:16
Expected  86% (70083140 of 81492023) |## | Elapsed Time: 0:08:46 ETA:   0:01:15
Expected  87% (70898061 of 81492023) |## | Elapsed Time: 0:08:54 ETA:   0:01:42
Expected  88% (71712981 of 81492023) |## | Elapsed Time: 0:09:01 ETA:   0:01:18
Expected  89% (72527901 of 81492023) |## | Elapsed Time: 0:09:09 ETA:   0:01:29
Expected  90% (73342821 of 81492023) |## | Elapsed Time: 0:09:15 ETA:   0:01:05
Expected  91% (74157741 of 81492023) |## | Elapsed Time: 0:09:21 ETA:   0:00:46
Expected  92% (74972662 of 81492023) |## | Elapsed Time: 0:09:26 ETA:   0:00:42
Expected  93% (75787582 of 81492023) |## | Elapsed Time: 0:09:31 ETA:   0:00:36
Expected  94% (76602502 of 81492023) |## | Elapsed Time: 0:09:36 ETA:   0:00:31
Expected  95% (77417422 of 81492023) |## | Elapsed Time: 0:09:42 ETA:   0:00:26
Expected  96% (78232343 of 81492023) |## | Elapsed Time: 0:09:47 ETA:   0:00:20
Expected  97% (79047263 of 81492023) |## | Elapsed Time: 0:09:52 ETA:   0:00:15
Expected  98% (79862183 of 81492023) |## | Elapsed Time: 0:09:57 ETA:   0:00:10
Expected  99% (80677103 of 81492023) |## | Elapsed Time: 0:10:08 ETA:   0:00:10
Expected 100% (81492023 of 81492023) |###| Elapsed Time: 0:10:14 Time:  0:10:14

**Comment by kaukrise** [comment]
Hi,

thanks for bringing this to our attention. I think this may be an instance where KR is "more stable" for bins with poor mappability.

Can you plot both of the original matrices in the same region (before fold-change calculation)? Once unnormalised and once normalised, please?

I would guess that the "unnatural" looking bin probably has very little signal in one of the samples. If that is the case, you can apply stricter filters for coverage using `fanc hic -n --norm-method ice -r 0.2 <hic file>`, for example (this also runs the ICE normalisation again). You may have to apply stricter cutoffs, but that should remedy the issue.

Cheers,

Kai

**Comment by xinyangbing** [comment]
Hey Kai,
We are taking our heatmaps for publication with cooler, and this extra filtering step might make the data different from the cooler files no? We want our virtual 4C data to be exactly the same as cooler. I was wondering if there's a way to feed the mcool files into the virtual 4C script instead? I tried just substituting the hic file with the mcool file in the Virtual4CPlot command in jupyterlab, and got an error:
import fanc
import numpy as np
import pandas as pd
import fanc.plotting as fancplot
hic = fanc.load("WT_genome_mcool/All_WT.mcool@800")
hp = fancplot.Virtual4CPlot(hic, viewpoint="chr3R:6,847,737-6,850,917", aspect=0.05,color="#648fff",draw_minor_ticks=False)
hp.plot('chr3R:6,815,279-6,918,278')
hp.show()

TypeError                                 Traceback (most recent call last)
<ipython-input-5-74e92da5b9ec> in <module>
      2 hic = fanc.load("WT_genome_mcool/All_WT.mcool@800")
      3 hp = fancplot.Virtual4CPlot(hic, viewpoint="chr3R:6,847,737-6,850,917", aspect=0.05,color="#648fff",draw_minor_ticks=False)
----> 4 hp.plot('chr3R:6,815,279-6,918,278')
      5 hp.show()

~/miniconda3/lib/python3.8/site-packages/fanc/plotting/base_plotter.py in plot(self, region)
    290             self.ax = plt.gca()
    291         self._before_plot(region)
--> 292         plot_output = self._plot(region)
    293         self._after_plot(region)
    294 

~/miniconda3/lib/python3.8/site-packages/fanc/plotting/plotter.py in _plot(self, region)
   1686 
   1687     def _plot(self, region):
-> 1688         submatrix = self.hic.matrix((self.viewpoint, region), norm=self.norm, oe=self.oe,
   1689                                     check_valid=self.check_valid, excluded_filters=self.excluded_filters,
   1690                                     mask=self.mask)

~/miniconda3/lib/python3.8/site-packages/fanc/matrix.py in matrix(self, key, log, default_value, mask, log_base, *args, **kwargs)
   1022         m = np.full((len(row_regions), len(col_regions)), default_value)
   1023 
-> 1024         for source, sink, weight in matrix_entries:
   1025             ir = source
   1026             jr = sink

~/miniconda3/lib/python3.8/site-packages/fanc/matrix.py in <genexpr>(.0)
    982 
    983         #edges_iter = self.edges((row_regions, col_regions), *args, **kwargs)
--> 984         entry_iter = ((i, j, weight)
    985                       for _, _, i, j, weight in offset_iter(edges_iter))
    986 

~/miniconda3/lib/python3.8/site-packages/fanc/matrix.py in offset_iter(edge_iter)
    968 
    969         def offset_iter(edge_iter):
--> 970             for edge in edge_iter:
    971                 source, sink, weight = edge.source, edge.sink, getattr(edge, score_field, self._default_value)
    972 

~/miniconda3/lib/python3.8/site-packages/fanc/matrix.py in __call__(self, key, *args, **kwargs)
    745                             ex = np.repeat(expected_inter, len(self._regions_pairs.regions))
    746 
--> 747                         for edge in self._regions_pairs._edges_subset(
    748                                 (GenomicRegion(row_chromosome,
    749                                                start=row_chromosome_regions[0].start,

~/miniconda3/lib/python3.8/site-packages/fanc/compatibility/cooler.py in _edges_subset(self, key, row_regions, col_regions, lazy, *args, **kwargs)
    435 
    436         for t in df.itertuples():
--> 437             yield self._tuple_to_edge(t, lazy_edge=lazy_edge, *args, **kwargs)
    438 
    439     def _edges_getitem(self, item, *args, **kwargs):

TypeError: _tuple_to_edge() got an unexpected keyword argument 'excluded_filters'

**Comment by kaukrise** [comment]
Hi, that is a bug, thanks for reporting it. I have uploaded a version with a fix that should work on the code you posted. Please update with

```
pip install --upgrade fanc
```

and confirm that you are running the latest version with `fanc -V` (`0.9.12`). It might take a bit before the new version is visible on Pypi!

**Comment by xinyangbing** [comment]
Hey sorry to bother you again. It is plotting now, but the virtual4Cplot function itself is running into some problem with the mcool file. For some reason, the upstream genomic region of the viewpoint is all zero. I plotted two regions of interest here:
<img width="1280" alt="Screen Shot 2021-01-28 at 4 26 59 PM" src="https://user-images.githubusercontent.com/55600546/106201051-e1192c00-6185-11eb-9eed-ae894b86802f.png">
<img width="1280" alt="Screen Shot 2021-01-28 at 4 27 23 PM" src="https://user-images.githubusercontent.com/55600546/106201058-e2e2ef80-6185-11eb-9ed7-664afa1f6ada.png">

**Comment by kaukrise** [comment]
Hey, sorry for all the trouble. I can reproduce the bug with the latest version, but haven't been able to trace it to its source. I will investigate more tomorrow, when I've had some sleep.

If you want, you can try the FAN-C development version, which uses a different (and faster) method for matrix retrieval. I tested it on an mcool file and the problem does not seem to occur there.

[fanc-0.9.12-dev.tar.gz](https://github.com/vaquerizaslab/fanc/files/5890334/fanc-0.9.12-dev.tar.gz)

You can install the above tarball using

```
pip install fanc-0.9.12-dev.tar.gz
```

I recommend doing this in a fresh virtual environment and keep the regular FAN-C version around for now, as the dev version hasn't been thoroughly tested for all functionality.

**Comment by kaukrise** [comment]
Hi again,

this was a tricky one to figure out, but I have uploaded a version with a fix that works on my local `mcool` test files. You can upgrade to `0.9.13` as outlined in one of the above posts. Please let me know if that fix works on your data, and apologies for the inconvenience!

Cheers,

Kai

**Comment by xinyangbing** [comment]
Hey Kai,
It's working as promised! Thank you so much for fixing this so fast!
David

**Comment by xinyangbing** [comment]
Hey Kai,

Sorry to bother you again. I kind of have no where to turn, and is a problem that pertains to the previous KR/ICE balancing problem. 
![image](https://user-images.githubusercontent.com/55600546/107448694-29363800-6b10-11eb-9a41-c067d6b3c846.png)
So turns out that MNase digestion is pretty unstable, and seems to introduce local variations especially at nucleosome depleted regions due to technical variation. I can see this with the marginals I plotted of this region, where the variation of coverage in this bin leads to aberrant behavior in normalization in ICE (which over-normalizes in one of our experimental replicates), and KR (which under-normalizes in the WT replicate I show). I was thinking that a potential fix for this would be to use the weights assigned for multiple replicates concatenated together, and then use these weights to balance replicates individually after. Unfortunately, there does not seem to be a built-in way to do this in Cooler, nor FAN-C. Currently, I am "black-listing" this bin, but it actually also happens to be exactly adjacent to a region of HIGH interest so it makes for quite an annoying lack of data there. 

Do you think this is something that would be useful to the community to add as a function in FAN-C? Please let me know if you have any other solutions. Thanks so much for the help!

**Comment by kaukrise** [comment]
Hi, I asked @liz-is for help and if we understand correctly your idea is to 

- Average the bias vector from all three replicates
- Use the "mean bias vector" to normalise the individual replicates

Is this correct? If so, while technically possible, I think this is not a valid approach. The bias vector is inherently sample-specific and should not be averaged across replicates, or applied to a different Hi-C matrix.

I would argue that masking (blacklisting) the bin is the correct approach already. I understand that your plots might not look as clean, but the artefact is a part of your data, after all. To me, masking the bin indicates a deliberate choice not to show data due to technical variability/issues, for which you have a good explanation.

**Comment by xinyangbing** [comment]
Okay thank you for confirming this. Always better to get a second opinion. While I appreciate for this instance my solution is a short term fix, I think long term we still have some inherent problems associated with Micro-C and the current balancing methods that requires a proper tackle. I'll shoot Liz and you a private email to follow up on this topic, and discuss possible solutions.
________________________________
